### ISSUE TITLE
Add `python_requires=">=3.8"`

### ISSUE THREAD

**Issue by matthewfeickert** [reanahub/reana-workflow-engine-yadage#221]
For similar motivations as https://github.com/reanahub/reana-client/pull/581 add `python_requires=">=3.8"` (given testing is only happening on Python 3.8 atm) to [`setup.py`](https://github.com/reanahub/reana-workflow-engine-yadage/blob/ac194f6d2972ea77642ba5d3f10d2da2173fff0e/setup.py#L66).

**Comment by mvidalgarcia** [comment]
No one is expected to install this package locally, this component is meant to run in a container where we define the actual python version.

While the change you suggest wouldn't hurt, it's not very relevant as we control the [python version](https://github.com/reanahub/reana-workflow-engine-yadage/blob/ac194f6d2972ea77642ba5d3f10d2da2173fff0e/Dockerfile#L8) ourselves at the container level.

**Comment by matthewfeickert** [comment]
> No one is expected to install this package locally, this component is meant to run in a container where we define the actual python version.

Sure. This Issue is a suggestion that isn't really for the benefit of CERN IT, but for anyone/everyone else who might ever try to do anything with this application.

I'm also just a general/unthinking advocate for making sure that every `setup.cfg`/`setup.py` that exists has a `python_requires` in it. It can only help.
