### ISSUE TITLE
cosmetics: non-recast verbiage

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-workflow-engine-yadage#25]
Spotted in a job output: 

```console
$ git grep  recast 
reana_workflow_engine_yadage/tasks.py:    log.info('running recast workflow on context: {ctx}'.format(ctx=ctx))
```

It would be good to say "running yadage workflow" here and elsewhere within the REANA ecosystem, so that the job output messages would be valid both in the REANA and RECAST contexts, as well as in any other instances where YADAGE workflow may be running.

**Comment by diegodelemos** [comment]
Closing, no more `recast` keyword in the module.
