### ISSUE TITLE
yadage: write workflow results to canonical location

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-workflow-engine-yadage#37]
```
<analysis_path>/results/plot.png
                       /paper.pdf
```

**Comment by lukasheinrich** [comment]
it's not clear to me what that means, a workflow might have multiple results that the user may be interested in, say in one run i'm interested in plot.png, on the next run in paper.pdf. In our proto-reana, the user passes a list of outputs that they are insterested in and those are then copied to a canonical location

**Comment by diegodelemos** [comment]
Fair enough. Then the question is: if the user specifies I want this list `['plot.png', 'paper.pdf']` she/he wont write the full path, will she/he? i.e. `['steptwo/plot.png', 'stepthree/paper.pdf']`

Are we running a "find" to get the file paths and moving them to the `<analysis_path>/results`?

**Comment by lukasheinrich** [comment]
in proto-reana we do this:

https://github.com/recast-hep/wflow-celery/blob/master/wflowcelery/backendtasks.py#L122

we cherry-pick a number of results that we upload/copy to a canonical place but delete everything else
